### PR TITLE
Default parameters file name fix

### PR DESCRIPTION
**Pull request by nicolasdanelon**

### CODE REVIEW

**Comment by nogo** [comment]
@nicolasdanelon thank for this fix

**Comment by nicolasdanelon** [comment]
@nogo your walcome, anytime. 
please can you add a password input? ;)

**Comment by nogo** [comment]
@nicolasdanelon You mean issue #76 ? You want to have the ability to change the password?

**Comment by nicolasdanelon** [comment]
Yes sr!

**Pull request merged**
